apiVersion: apps/v1
kind: Deployment
metadata:
  name: yek-ray-scraper
  namespace: yek-ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: your-docker-registry/oliveyoung-crawler:latest
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: config-volume
              mountPath: /app/oliveyoung/settings.py
              subPath: settings.py
      volumes:
        - name: config-volume
          configMap:
            name: oliveyoung-settings
