apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: yek-ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        # image: your-registry/scraper:latest
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
          - name: config-volume
            mountPath: /app/oliveyoung/settings.py
            subPath: settings.py
        env:
          - name: RAY_HEAD_SERVICE
            value: ray-cluster-head-svc