apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: product-ray-job
  namespace: yek-ray
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: product-ray
          image: koreantiger/ray-scrapy:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
            - |
              pip install scrapy==2.8.0 Twisted==22.10.0 pymongo==4.10.1 dnspython==2.6.1 ray[client]==2.9.0 &&
              python ./oliveyoung/spiders/product_ray.py
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017"
            - name: CLUSTER_DOMAIN
              value: "ops.openark"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HEAD_SERVICE_NAME
              value: "ray-cluster-head-svc"
            - name: RAY_ADDRESS
              value: "ray://raycluster-complete-head-svc:10001"
